#!/bin/sh

uci -q batch <<-EOF >/dev/null
# /etc/config/system
    set system.@system[0].timezone='CST-8'
    set system.@system[0].zonename='Asia/Shanghai'
    commit system

# /etc/config/network
    set network.lan.ipaddr='192.168.5.1'
    commit network

# /etc/config/wireless
    set wireless.radio0.disabled='0'
    set wireless.radio0.channel='149'
    set wireless.default_radio0.key='password123'
    set wireless.default_radio0.ssid='ATV'
    set wireless.default_radio0.encryption='psk2+ccmp'

    set wireless.radio1.disabled='0'
    set wireless.radio1.channel='1'
    set wireless.default_radio1.key='password123'
    set wireless.default_radio1.ssid='ATV'
    set wireless.default_radio1.encryption='psk2+ccmp'

    set wireless.radio2.disabled='0'
    set wireless.radio2.channel='36'
    set wireless.default_radio2.key='password123'
    set wireless.default_radio2.ssid='ATV'
    set wireless.default_radio2.encryption='psk2+ccmp'

    commit wireless

# /etc/config/smartdns
    set smartdns.@smartdns[0].enabled='1'
    set smartdns.@smartdns[0].ui='1'
    # for openwrt-22.03
    set smartdns.@smartdns[0].port='6053'
    # for openwrt-22.03
    #set smartdns.@smartdns[0].auto_set_dnsmasq='1'

    set smartdns.@smartdns[0].cache_size='12288'
    set smartdns.@smartdns[0].cache_persist='1'
    set smartdns.@smartdns[0].rr_ttl_min='600'
    set smartdns.@smartdns[0].prefetch_domain='1'
    set smartdns.@smartdns[0].serve_expired='1'
    set smartdns.@smartdns[0].force_https_soa='1'

    set smartdns.@smartdns[0].speed_check_mode='none'
    set smartdns.@smartdns[0].response_mode='fastest-ip'

    set smartdns.@smartdns[0].enable_auto_update='1'
    set smartdns.@smartdns[0].auto_update_week_time='1'
    set smartdns.@smartdns[0].auto_update_day_time='5'

    set smartdns.@smartdns[0].seconddns_enabled='1'
    #set smartdns.@smartdns[0].seconddns_port='6553'
    set smartdns.@smartdns[0].seconddns_server_group='pw'
    set smartdns.@smartdns[0].seconddns_no_speed_check='1'
    set smartdns.@smartdns[0].seconddns_force_aaaa_soa='1'
    set smartdns.@smartdns[0].seconddns_force_https_soa='1'

    set smartdns.@smartdns[0].log_level='debug'
    set smartdns.@smartdns[0].log_size='128k'
    set smartdns.@smartdns[0].log_num='2'
    set smartdns.@smartdns[0].enable_audit_log='1'
    set smartdns.@smartdns[0].audit_log_size='128k'
    set smartdns.@smartdns[0].audit_log_num='2'

    set smartdns.@smartdns[0].proxy_server='socks5://127.0.0.1:1070'

    add smartdns server # =cfg02769c
    set smartdns.@server[0].name='Aliyun'
    set smartdns.@server[0].server_group='cn'
    set smartdns.@server[0].ip='223.5.5.5'

    add smartdns server # =cfg03769c
    set smartdns.@server[1].name='DNSPod'
    set smartdns.@server[1].server_group='cn'
    set smartdns.@server[1].ip='119.29.29.29'

    add smartdns server # =cfg04769c
    set smartdns.@server[2].name='Baidu'
    set smartdns.@server[2].server_group='cn'
    set smartdns.@server[2].ip='180.76.76.76'

    add smartdns server # =cfg05769c
    set smartdns.@server[3].name='Cloudflare'
    set smartdns.@server[3].exclude_default_group='1'
    set smartdns.@server[3].server_group='pw'
    set smartdns.@server[3].type='tls'
    set smartdns.@server[3].ip='1.1.1.1'
    set smartdns.@server[3].use_proxy='1'

    add smartdns server # =cfg06769c
    set smartdns.@server[4].name='Google'
    set smartdns.@server[4].exclude_default_group='1'
    set smartdns.@server[4].server_group='pw'
    set smartdns.@server[4].type='tls'
    set smartdns.@server[4].ip='8.8.8.8'
    set smartdns.@server[4].use_proxy='1'

    add smartdns server # =cfg07769c
    set smartdns.@server[5].name='OpenDNS'
    set smartdns.@server[5].exclude_default_group='1'
    set smartdns.@server[5].server_group='pw'
    set smartdns.@server[5].type='tls'
    set smartdns.@server[5].ip='208.67.222.222'
    set smartdns.@server[5].use_proxy='1'

    add smartdns download-file # =cfg0b0e4a
    set smartdns.@download-file[0].name='anti-ad-for-smartdns.conf'
    set smartdns.@download-file[0].url='https://neodev.team/smartdns.conf'
    set smartdns.@download-file[0].type='config'

    commit smartdns

# /etc/config/dhcp
    #add_list dhcp.@dnsmasq[0].server='127.0.0.1#6053'
    #set dhcp.@dnsmasq[0].noresolv='1'

    #set dhcp.lan.ra='relay'
    #set dhcp.lan.dhcpv6='relay'
    #set dhcp.lan.ndp='relay'

    #set dhcp.wan6=dhcp
    #set dhcp.wan6.interface='wan6'
    #set dhcp.wan6.ignore='1'
    #set dhcp.wan6.master='1'
    #set dhcp.wan6.ra='relay'
    #set dhcp.wan6.dhcpv6='relay'
    #set dhcp.wan6.ndp='relay'

    #commit dhcp

# /etc/config/AdGuardHome
    #set AdGuardHome.AdGuardHome.enabled='1'
    #set AdGuardHome.AdGuardHome.redirect='redirect'
    #commit AdGuardHome

# /etc/config/adblock
    #set adblock.global.adb_triggerdelay='120'
    #commit adblock

# /etc/config/vlmcsd
    set vlmcsd.config.enabled='1'
    set vlmcsd.config.auto_activate='1'
    commit vlmcsd

# /etc/config/sqm
    set sqm.eth1.enabled='1'
    set sqm.eth1.interface='wan'
    set sqm.eth1.download='300000'
    set sqm.eth1.upload='30000'
    commit sqm
EOF

cat >> /etc/smartdns/address.conf <<-EOF
conf-file /etc/smartdns/conf.d/anti-ad-for-smartdns.conf
EOF

cat >> /etc/smartdns/custom.conf <<-EOF

# cache persist file
cache-file /var/etc/smartdns/smartdns.cache

# prefetch domain
serve-expired-prefetch-time 43200

# cache serve expired TTL
serve-expired-ttl 345600

# Support reading dnsmasq dhcp file to resolve local hostname
#dnsmasq-lease-file /tmp/dhcp.leases

edns-client-subnet 60.177.72.0/21
EOF

passwd root <<EOF
password
password
EOF

sed -i '/^cn$/d' /usr/share/passwall/rules/direct_host
sed -i '1i\c.hegre.com\np.hegre.com\ncontent.hegre.com\ncc.hegre.com\npp.hegre.com' /usr/share/passwall/rules/direct_host
sed -i '1i\205.185.216.10\n205.185.216.42\n156.146.53.32\n156.146.53.33\n156.146.53.35\n156.146.53.36' /usr/share/passwall/rules/direct_ip

sed -i '/passwall/d ; /helloworld/d ; /openclash/d' /etc/opkg/distfeeds.conf

exit 0
