#!/bin/sh

uci -q batch <<-EOF >/dev/null
# /etc/config/system
    set system.@system[0].timezone='CST-8'
    set system.@system[0].zonename='Asia/Shanghai'
    commit system

# /etc/config/network
    #set network.lan.ipaddr='192.168.5.1'
    #commit network

# /etc/config/smartdns
    #set smartdns.@smartdns[0].enabled='1'
    set smartdns.@smartdns[0].ui='1'
    # for openwrt-22.03
    #set smartdns.@smartdns[0].port='6053'
    # for openwrt-22.03
    #set smartdns.@smartdns[0].auto_set_dnsmasq='1'

    #set smartdns.@smartdns[0].cache_size='12288'
    #set smartdns.@smartdns[0].cache_persist='1'
    #set smartdns.@smartdns[0].rr_ttl_min='600'
    #set smartdns.@smartdns[0].prefetch_domain='1'
    #set smartdns.@smartdns[0].serve_expired='1'
    #set smartdns.@smartdns[0].force_https_soa='1'

    #set smartdns.@smartdns[0].speed_check_mode='ping'
    #set smartdns.@smartdns[0].response_mode='fastest-ip'

    #set smartdns.@smartdns[0].seconddns_enabled='1'
    #set smartdns.@smartdns[0].seconddns_port='6553'
    #set smartdns.@smartdns[0].seconddns_server_group='pw'
    #set smartdns.@smartdns[0].seconddns_no_speed_check='1'
    #set smartdns.@smartdns[0].seconddns_force_aaaa_soa='1'
    #set smartdns.@smartdns[0].seconddns_force_https_soa='1'

    #set smartdns.@smartdns[0].enable_auto_update='1'
    #set smartdns.@smartdns[0].auto_update_week_time='1'
    #set smartdns.@smartdns[0].auto_update_day_time='5'

    #set smartdns.@smartdns[0].log_level='debug'
    #set smartdns.@smartdns[0].log_size='128k'
    #set smartdns.@smartdns[0].log_num='2'
    #set smartdns.@smartdns[0].enable_audit_log='1'
    #set smartdns.@smartdns[0].audit_log_size='128k'
    #set smartdns.@smartdns[0].audit_log_num='2'

    #add smartdns server # =cfg02769c
    #set smartdns.@server[0].name='Aliyun'
    #set smartdns.@server[0].ip='223.5.5.5'
    #set smartdns.@server[0].server_group='cn'

    #add smartdns server # =cfg03769c
    #set smartdns.@server[1].name='DNSPod'
    #set smartdns.@server[1].ip='119.29.29.29'
    #set smartdns.@server[1].server_group='cn'

    #add smartdns server # =cfg04769c
    #set smartdns.@server[2].name='Baidu'
    #set smartdns.@server[2].ip='180.76.76.76'
    #set smartdns.@server[2].server_group='cn'

    #add smartdns server # =cfg05769c
    #set smartdns.@server[3].name='Cloudflare'
    #set smartdns.@server[3].ip='1.1.1.1'
    #set smartdns.@server[3].type='tls'
    #set smartdns.@server[3].server_group='pw'
    #set smartdns.@server[3].exclude_default_group='1'
    #set smartdns.@server[3].tls_host_verify='cloudflare-dns.com'
    #set smartdns.@server[3].no_check_certificate='1'
    #set smartdns.@server[3].addition_arg='-check-edns'

    #add smartdns server # =cfg06769c
    #set smartdns.@server[4].name='Google'
    #set smartdns.@server[4].ip='8.8.8.8'
    #set smartdns.@server[4].type='tls'
    #set smartdns.@server[4].server_group='pw'
    #set smartdns.@server[4].exclude_default_group='1'
    #set smartdns.@server[4].tls_host_verify='dns.google'
    #set smartdns.@server[4].no_check_certificate='1'
    #set smartdns.@server[4].addition_arg='-check-edns'

    #add smartdns server # =cfg07769c
    #set smartdns.@server[5].name='OpenDNS'
    #set smartdns.@server[5].ip='208.67.222.222'
    #set smartdns.@server[5].type='tls'
    #set smartdns.@server[5].server_group='pw'
    #set smartdns.@server[5].exclude_default_group='1'
    #set smartdns.@server[5].tls_host_verify='dns.opendns.com'
    #set smartdns.@server[5].no_check_certificate='1'
    #set smartdns.@server[5].addition_arg='-check-edns'

    #add smartdns download-file # =cfg0b0e4a
    #set smartdns.@download-file[0].name='anti-ad-for-smartdns.conf'
    #set smartdns.@download-file[0].url='https://neodev.team/smartdns.conf'
    #set smartdns.@download-file[0].type='config'

    commit smartdns

# /etc/config/vlmcsd
    #set vlmcsd.config.enabled='1'
    #set vlmcsd.config.auto_activate='1'
    #commit vlmcsd

# /etc/config/sqm
    #set sqm.eth1.enabled='1'
    #set sqm.eth1.interface='wan'
    #set sqm.eth1.download='300000'
    #set sqm.eth1.upload='30000'
    #commit sqm

# /etc/config/irqbalance
    set irqbalance.irqbalance.enabled='1'
    commit irqbalance
EOF

#passwd root <<EOF
#password
#password
#EOF

sed -i '/^cn$/d' /usr/share/passwall/rules/direct_host
sed -i '1i\www.msftncsi.com\nwww.msftconnecttest.com\ndns.msftncsi.com' /usr/share/passwall/rules/direct_host
sed -i '1i\browserleaks.net\nbrowserleaks.org\nipleak.net' /usr/share/passwall/rules/proxy_host
sed -i 's/geosite:cn/geosite:geolocation-cn/g' /usr/share/passwall/0_default_config

exit 0
